package com.example.android.unscramble.ui.game


const val MAX_NO_OF_WORDS = 10
const val SCORE_INCREASE = 20

// List with all the words for the Game
val allWordsList: List<String> =
    listOf("mobil",
        "ikan",
        "lampu",
        "kaca",
        "television",
        "mouse",
        "pouch",
        "ransel",
        "flatshoes",
        "kemeja",
        "antibodi",
        "antibiotik",
        "serikaya",
        "charger",
        "parfume",
        "figura",
        "halaman",
        "sarung",
        "manggis",
        "mengkudu",
        "mousepad",
        "kamera",
        "kemarau",
        "hoodie",
        "kambing",
        "virus",
        "jendela",
        "buku",
        "android",
        "permainan",
        "monitor",
        "pintu",
        "pisang",
        "kelapa",
        "markisa",
        "nanas",
        "kerupuk",
        "kelengkeng",
        "pepaya",
        "kepiting",
        "biawak",
        "komodo",
        "bunglon",
        "kucing",
        "kodok",
        "piring",
        "gelas",
        "pisau",
        "garpu",
        "sendok",
        "speedboat",
        "kereta",
        "becak",
        "angkot",
        "bus",
        "pesawat"
        )